spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: workflow-processor-group
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
  application:
    name: workflow-processor

server:
  port: 8082


